#Database connection Parameters
url=jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=CONVERT_TO_NULL
driver=com.mysql.jdbc.Driver
username=root
password=root
#DATABASE=JDBC
#service=javaBean
acquireIncrement = 10
initialPoolSize = 10
maxPoolSize = 100
minPoolSize = 10
timeout = 10


paypal.client.id=AXJOq_IBRksXX0ROPtCoj1NR1MAUbInKQzuK75joBSPRX9FdtiioZjlCrGZ0xkTWIOcqeVqjJw0tUUvf
paypal.client.secret=ELFI-Zmn-Mct6gnnd8PI7TtOazqk2c9Zrhs92MFpbjhsHFbeqH8AvckFu5mUj5gE7iASCExddAwwXUED
paypal.mode=sandbox